#!/bin/bash

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/conf.sh"

checkSudo
checkScriptParams

commandList() {
    echo "SUDO REQUIRED!!!"
    echo "Command list:"
    echo "kall - Kill all workers and command disatcher"
    echo "krecievers - Kill reciever workers"
    echo "ksenders - Kill sender workers"
    echo "kupdaters - Kill updaters workers"
    echo "kdispatcher - Kill command dispatcher"
    echo "restart - restart workers"
    echo "ps - get workers list"
    echo "rabbit_lq - equialent for rabbitmqctl list_queues"
}

if [ -z "$1" ]
   then
        commandList
   exit 1
fi

case "$1" in
               "kall")
                    pkill -f "queuemail"
                    pkill -f "queue_workers"
                    ;;
               "krecievers")
                    pkill -f "queuemailreceiver"
                    ;;
               "ksenders")
                     pkill -f "queuemailsender"
                     ;;
               "kupdaters")
                     pkill -f "queuemailupdaterstatus"
                     ;;
               "ps")
                     ps aux | grep 'console.php' | grep -v 'grep'
                     ;;

               "rabbit_lq")
                     rabbitmqctl list_queues
                     ;;
               "kdispatcher")
                     pkill -f "queue_workers"
                     ;;
               "restart")
                      pkill -f "queuemail"
                      pkill -f "queue_workers"
                      startBashCommand "queue_workers"
                     ;;
               *)
                     commandList
                     ;;
            esac


