#!/bin/bash

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
. "$DIR/conf.sh"

checkSudo
checkScriptParams

for processName in "$LIST_WORKERS"
do
    PROCESS_RUN=0
    PROCESS_COUNTER=$(getProcessCounter $processName)

    if [ -z "$PROCESS_COUNTER" ]
    then
        startBashCommand "$processName"
    else
        if [[ $PROCESS_COUNTER -gt 1 ]]
        then
            startBashCommand "$processName"
        else
            killProcess $processName
            echo "$processName running."
        fi
    fi
done

